eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true

  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  appConfig: feign-server, feign-upload-client
  clusterNameExpression: "'default'"