server:
  port: 8013

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  server:
    enableSelfPreservation: false

instance:
  prefer-ip-address: true

